version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:11.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE:-splinter-research}
      MYSQL_USER: ${MARIADB_USER:-splinter-research}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
      --max-connections=1000
      --max-user-connections=950
      --thread-cache-size=100
      --table-open-cache=4000
      --innodb-buffer-pool-size=2G
      --innodb-log-file-size=512M
      --innodb-log-buffer-size=64M
      --innodb-flush-log-at-trx-commit=2
      --query-cache-type=1
      --query-cache-size=128M
      --tmp-table-size=256M
      --max-heap-table-size=256M
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Client for bucket initialization
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-noctipede-data}
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set minio http://minio:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      /usr/bin/mc mb minio/$${MINIO_BUCKET_NAME} --ignore-existing;
      /usr/bin/mc policy set public minio/$${MINIO_BUCKET_NAME};
      exit 0;
      "

  # Noctipede Application
  noctipede-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      # Database
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_USER: ${MARIADB_USER:-splinter-research}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-splinter-research}
      
      # MinIO
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-noctipede-data}
      MINIO_SECURE: "false"
      
      # AI/Ollama
      OLLAMA_ENDPOINT: ${OLLAMA_ENDPOINT}
      OLLAMA_VISION_MODEL: ${OLLAMA_VISION_MODEL:-llama3.2-vision:11b}
      OLLAMA_TEXT_MODEL: ${OLLAMA_TEXT_MODEL:-gemma3:12b}
      OLLAMA_MODERATION_MODEL: ${OLLAMA_MODERATION_MODEL:-llama3.1:8b}
      
      # Application
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      OUTPUT_DIR: /app/output
      SITES_FILE_PATH: /app/data/sites.txt
      
      # Crawler settings
      MAX_LINKS_PER_PAGE: ${MAX_LINKS_PER_PAGE:-50}
      MAX_QUEUE_SIZE: ${MAX_QUEUE_SIZE:-500}
      CRAWL_DELAY_SECONDS: ${CRAWL_DELAY_SECONDS:-3}
      MAX_CONCURRENT_CRAWLERS: ${MAX_CONCURRENT_CRAWLERS:-10}
      
      # Network settings
      TOR_PROXY_HOST: ${TOR_PROXY_HOST:-127.0.0.1}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT:-9050}
      I2P_PROXY_HOST: ${I2P_PROXY_HOST:-127.0.0.1}
      I2P_PROXY_PORT: ${I2P_PROXY_PORT:-4444}
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./logs:/app/logs
    command: ["python", "-m", "noctipede.crawlers.main"]

  # Noctipede Web Interface
  noctipede-web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      # Database
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_USER: ${MARIADB_USER:-splinter-research}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-splinter-research}
      
      # MinIO
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-noctipede-data}
      MINIO_SECURE: "false"
      
      # Web server
      WEB_SERVER_HOST: 0.0.0.0
      WEB_SERVER_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    command: ["python", "-m", "noctipede.api.main"]

volumes:
  mariadb_data:
    driver: local
  minio_data:
    driver: local

networks:
  default:
    name: noctipede-network
