apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"i2p-proxy","component":"proxy"},"name":"i2p-data-pvc","namespace":"noctipede"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"longhorn"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-07-04T03:58:18Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: i2p-proxy
      component: proxy
    name: i2p-data-pvc
    namespace: noctipede
    resourceVersion: "1823689"
    uid: 38fe33c9-8eb2-4de5-9b7f-3df9682536c2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-38fe33c9-8eb2-4de5-9b7f-3df9682536c2
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"minio-storage","namespace":"noctipede"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Gi"}},"storageClassName":"longhorn"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-07-04T03:53:32Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: minio-storage
    namespace: noctipede
    resourceVersion: "1820087"
    uid: 6dcd2f5a-9395-4eb6-9678-165005d6ee51
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-6dcd2f5a-9395-4eb6-9678-165005d6ee51
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"noctipede-logs-pvc","namespace":"noctipede"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"longhorn"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-07-04T04:06:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: noctipede-logs-pvc
    namespace: noctipede
    resourceVersion: "1829938"
    uid: c278d4a8-d38e-40c4-9dde-a4b09e068f2d
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-c278d4a8-d38e-40c4-9dde-a4b09e068f2d
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"noctipede-output-pvc","namespace":"noctipede"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"20Gi"}},"storageClassName":"longhorn"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-07-04T04:06:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: noctipede-output-pvc
    namespace: noctipede
    resourceVersion: "1829941"
    uid: 7ecf13f3-bcdd-423a-b38e-a1afbe8306b4
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-7ecf13f3-bcdd-423a-b38e-a1afbe8306b4
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"noctipede-sites-pvc","namespace":"noctipede"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"longhorn"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-07-04T04:06:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: noctipede-sites-pvc
    namespace: noctipede
    resourceVersion: "1829933"
    uid: c121bb2c-bb3c-4048-8d71-611e1c6de111
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-c121bb2c-bb3c-4048-8d71-611e1c6de111
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-07-04T03:53:31Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: mariadb
      app.kubernetes.io/name: mariadb
      pvc.k8s.mariadb.com/role: storage
    name: storage-mariadb-0
    namespace: noctipede
    resourceVersion: "1820077"
    uid: de068d1e-7f45-4ff2-a26f-4c7b7dbe871d
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-de068d1e-7f45-4ff2-a26f-4c7b7dbe871d
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"tor-proxy","component":"proxy"},"name":"tor-data-pvc","namespace":"noctipede"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"longhorn"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-07-04T03:54:10Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: tor-proxy
      component: proxy
    name: tor-data-pvc
    namespace: noctipede
    resourceVersion: "1820773"
    uid: 2fcccf1f-2f9f-4fd5-a990-6b80c57d5e5c
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-2fcccf1f-2f9f-4fd5-a990-6b80c57d5e5c
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
