apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-crawler
  namespace: noctipede
spec:
  # reference the secret you just created
  configuration:
    name: minio-crawler-config

  # Disable TLS completely
  requestAutoCert: false
  
  # expose both the S3 API and the Console
  exposeServices:
    minio: true
    console: true

  pools:
    - name: minio-crawler
      servers: 3             # 3 pods for erasure-coded distributed storage
      volumesPerServer: 4    # each pod has 4 Longhorn volumes
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi
          storageClassName: longhorn

      # Configure resource limits
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 2Gi

      # Security context
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true

  # Environment variables for MinIO
  env:
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: "public"
    - name: MINIO_BROWSER_REDIRECT_URL
      value: "http://minio-crawler-console.noctipede:9001"
