---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: noctipede
type: Opaque
data:
  # AKIA6V7J3N9B5P0D2YQH (base64 encoded)
  access-key: QUtJQTZWN0ozTjlCNVAwRDJZUUg=
  # 8fG3!v2rJ7$wN@9mLpQ6zXbC4tKdPqW1 (base64 encoded)
  secret-key: OGZHMyF2MnJKNyR3TkA5bUxwUTZ6WGJDNHRLZFBxVzE=

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  namespace: noctipede
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: noctipede
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: "public"
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: storage
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-storage

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: noctipede
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    name: api
  - port: 9001
    targetPort: 9001
    name: console
  selector:
    app: minio

---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: noctipede
  labels:
    app: minio
spec:
  type: LoadBalancer
  ports:
  - port: 9001
    targetPort: 9001
    name: console
  selector:
    app: minio
