apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: splinter-research
  namespace: noctipede
spec:
  mariaDbRef:
    name: mariadb
  name: splinter-research
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
