apiVersion: v1
kind: Service
metadata:
  name: mariadb-simple
  namespace: noctipede
  labels:
    app: mariadb-simple
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mariadb-simple
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-simple
  namespace: noctipede
spec:
  serviceName: mariadb-simple
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-simple
  template:
    metadata:
      labels:
        app: mariadb-simple
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIA_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "splinter-research"
        - name: MYSQL_USER
          value: "splinter-research"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIA_USER_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --max-connections=1000
        - --max-allowed-packet=256M
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: longhorn
      resources:
        requests:
          storage: 50Gi
