apiVersion: batch/v1
kind: CronJob
metadata:
  name: noctipede-crawler-nfs
  namespace: noctipede
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: wait-for-services
            image: busybox:1.35
            command: ['sh', '-c']
            args:
            - |
              echo "🔍 Waiting for required services..."
              until nc -z mariadb 3306; do
                echo "⏳ MariaDB not ready, waiting..."
                sleep 5
              done
              echo "✅ MariaDB is ready!"
              
              until nc -z minio 9000; do
                echo "⏳ MinIO not ready, waiting..."
                sleep 5
              done
              echo "✅ MinIO is ready!"
              
              until nc -z tor-proxy 9150; do
                echo "⏳ Tor proxy not ready, waiting..."
                sleep 5
              done
              echo "✅ Tor proxy is ready!"
              
              until nc -z i2p-proxy 4444; do
                echo "⏳ I2P proxy not ready, waiting..."
                sleep 5
              done
              echo "✅ I2P proxy is ready!"
              
          - name: verify-sites-file
            image: busybox:1.35
            command: ['sh', '-c']
            args:
            - |
              echo "📋 Verifying sites.txt file from NFS..."
              if [ -f /nfs-sites/sites.txt ]; then
                echo "✅ Found sites.txt with $(wc -l < /nfs-sites/sites.txt) sites"
                echo "📄 First 5 sites:"
                head -5 /nfs-sites/sites.txt
              else
                echo "❌ sites.txt not found in NFS mount!"
                echo "📁 NFS directory contents:"
                ls -la /nfs-sites/
                exit 1
              fi
            volumeMounts:
            - name: sites-nfs
              mountPath: /nfs-sites
              
          containers:
          - name: noctipede-crawler
            image: ghcr.io/splinterstice/noctipede:i2p-database-fix
            imagePullPolicy: Always
            command: ["sh", "-c"]
            args:
            - |
              echo "🚀 Starting Noctipede Crawler with NFS sites..."
              cd /app
              
              # Use NFS-mounted sites.txt
              export SITES_FILE_PATH=/nfs-sites/sites.txt
              
              echo "📋 Using sites file: $SITES_FILE_PATH"
              echo "📊 Total sites to crawl: $(wc -l < $SITES_FILE_PATH)"
              
              # Start crawler
              PYTHONPATH=/app python -m crawlers.main
              
            envFrom:
            - configMapRef:
                name: noctipede-config
            - secretRef:
                name: noctipede-secrets
            env:
            - name: SITES_FILE_PATH
              value: "/nfs-sites/sites.txt"
            - name: LOG_LEVEL
              value: "INFO"
            - name: OLLAMA_KEEP_ALIVE
              value: "30s"
            - name: OLLAMA_CONCURRENT_REQUESTS
              value: "1"
            - name: AI_MODEL_UNLOAD_AFTER_USE
              value: "true"
            - name: CONTENT_ANALYSIS_ENABLED
              value: "false"
            - name: IMAGE_ANALYSIS_ENABLED
              value: "false"
            volumeMounts:
            - name: sites-nfs
              mountPath: /nfs-sites
              readOnly: true
            - name: output-data
              mountPath: /app/output
            - name: log-data
              mountPath: /app/logs
              
          volumes:
          - name: sites-nfs
            persistentVolumeClaim:
              claimName: noctipede-sites-pvc
          - name: output-data
            persistentVolumeClaim:
              claimName: noctipede-output-pvc
          - name: log-data
            persistentVolumeClaim:
              claimName: noctipede-logs-pvc
              
          restartPolicy: OnFailure
