apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noctipede-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd
  labels:
    app: flame
spec:
  rules:
    - host: noctipede.splinterstice.celestium.life
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: noctipede-portal
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noctipede-https
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: ca-issuer
  labels:
    app: noctipede-portal
spec:
  rules:
    - host: noctipede.splinterstice.celestium.life
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: noctipede-portal
                port:
                  number: 8080
  tls:
    - hosts:
        - noctipede.splinterstice.celestium.life
      secretName: noctipede-cert
