apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noctipede-https
  namespace: noctipede
  labels:
    app: noctipede-portal
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
    - noctipede.splinterstice.celestium.life
    secretName: noctipede-cert
  rules:
  - host: noctipede.splinterstice.celestium.life
    http:
      paths:
      # Route to the stable portal service temporarily
      - path: /
        pathType: Prefix
        backend:
          service:
            name: noctipede-portal-service
            port:
              number: 8080
