apiVersion: v1
kind: Secret
metadata:
  name: noctipede-secrets
  namespace: noctipede
type: Opaque
stringData:
  # Database credentials
  MARIADB_PASSWORD: "PSCh4ng3me!"
  MARIADB_ROOT_PASSWORD: "strongRootPassword"
  
  # MinIO credentials
  MINIO_ACCESS_KEY: "AKIA6V7J3N9B5P0D2YQH"
  MINIO_SECRET_KEY: "8fG3!v2rJ7$wN@9mLpQ6zXbC4tKdPqW1"
  
  # Ollama endpoint (update with your actual endpoint)
  OLLAMA_ENDPOINT: "http://10.1.1.12:2701/api/generate"
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: noctipede
type: Opaque
stringData:
  MARIA_ROOT_PASSWORD: "strongRootPassword"
  MARIA_USER_PASSWORD: "PSCh4ng3me!"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-crawler-config
  namespace: noctipede
stringData:
  config.env: |
    # MinIO root credentials
    export MINIO_ROOT_USER=AKIA6V7J3N9B5P0D2YQH
    export MINIO_ROOT_PASSWORD=8fG3!v2rJ7$wN@9mLpQ6zXbC4tKdPqW1

    # Console admin (optional)
    export MINIO_CONSOLE_ADMIN_USER=admin
    export MINIO_CONSOLE_ADMIN_PASSWORD=S3cur3C0ns0le

    # Performance optimizations for distributed setup
    export MINIO_DISTRIBUTED_NODES=3
    
    # Enable browser/console
    export MINIO_BROWSER=on
    
    # Health check settings
    export MINIO_HEALTH_CHECK_MAX_REQUEST_SIZE=16384
    
    # Set proper API signature version
    export MINIO_API_SIGNATURE_V2=off
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: noctipede
stringData:
  # These should match your deployment.yaml expectations
  MINIO_ACCESS_KEY: "AKIA6V7J3N9B5P0D2YQH"
  MINIO_SECRET_KEY: "8fG3!v2rJ7$wN@9mLpQ6zXbC4tKdPqW1"
  rootUser: "AKIA6V7J3N9B5P0D2YQH"
  rootPassword: "8fG3!v2rJ7$wN@9mLpQ6zXbC4tKdPqW1"
type: Opaque
