apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"minio-storage","namespace":"noctipede"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Gi"}},"storageClassName":"longhorn"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-07-04T20:05:38Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: minio-storage
    namespace: noctipede
    resourceVersion: "2455556"
    uid: f4c727b6-11f7-40ac-91fc-180edc122b1c
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-f4c727b6-11f7-40ac-91fc-180edc122b1c
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2025-07-04T20:05:37Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: mariadb
      app.kubernetes.io/name: mariadb
      pvc.k8s.mariadb.com/role: storage
    name: storage-mariadb-0
    namespace: noctipede
    resourceVersion: "2455535"
    uid: ad2d268a-8e7c-49ca-bdbb-2cbf2681aa6a
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-ad2d268a-8e7c-49ca-bdbb-2cbf2681aa6a
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
