apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noctipede-sites-pvc-rwx
  namespace: noctipede
  labels:
    app: noctipede
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noctipede-output-pvc-rwx
  namespace: noctipede
  labels:
    app: noctipede
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noctipede-logs-pvc-rwx
  namespace: noctipede
  labels:
    app: noctipede
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
