apiVersion: v1
kind: Service
metadata:
  name: noctipede-web-service
  namespace: noctipede
  labels:
    app: noctipede-web
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: noctipede-web
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: noctipede-app-service
  namespace: noctipede
  labels:
    app: noctipede-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: noctipede-app
